# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Labrador-and-Golden-Retriever-Classifier',
                'doc_host': 'https://jerryweijin.github.io',
                'git_url': 'https://github.com/jerryweijin/Labrador-and-Golden-Retriever-Classifier',
                'lib_path': 'Labrador_and_Golden_Retriever_Classifier'},
  'syms': { 'Labrador_and_Golden_Retriever_Classifier.core': { 'Labrador_and_Golden_Retriever_Classifier.core.foo': ( 'core.html#foo',
                                                                                                                      'Labrador_and_Golden_Retriever_Classifier/core.py')}}}
